version: '3'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: quotes-api-image
    container_name: quotes-api
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3333:3333
    command: yarn start
